# Working Conditions 

## About your current job

Includes questions 2-8, codes: WCJC001, WCJC003, WCJC004, WCJC005, WCJ005a, WCJC010, WCJC011. 


### `r varlabel("WCJC001")`

```{r your_position, eval=varexists("WCJC001") }
data %>% 
    filter(!is.na(WCJC001) & hideNA) %>% 
    ggplot(aes(x=WCJC001, fill=WCJC001)) + 
    geom_bar()+ 
    scale_fill_brewer(palette="Set1") +
    guides(fill=F) +
    labs(y="Total count") +
    theme_light() +
    theme(axis.title.x = element_blank())
```


```{r your_position_tab, eval=varexists("WCJC001")}

print_frqtable(data$WCJC001) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("WCJC003")`

```{r academic_field, eval=varexists("WCJC003"), fig.width=10, fig.height=10}
data %>% 
    filter(!is.na(WCJC003) & hideNA) %>% 
    ggplot(aes(x=WCJC003, fill=WCJC003)) + 
    geom_bar() + 
    coord_flip() + 
    scale_fill_brewer(palette="Set1") +
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r academic_field_tab, eval=varexists("WCJC003")}

print_frqtable(data$WCJC003) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>

### `r varlabel("WCJC003PL")`

```{r academic_field_PL, eval=varexists("WCJC003PL"), fig.width=10, fig.height=10}
data %>% 
    filter(!is.na(WCJC003PL) & hideNA) %>% 
    ggplot(aes(x=WCJC003PL, fill=WCJC003PL)) + 
    geom_bar() + 
    coord_flip() + 
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r academic_field_tab_PL, eval=varexists("WCJC003PL")}

print_frqtable(data$WCJC003PL) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("WCJC004")`
```{r your_post, eval=varexists("WCJC004"), fig.width=8, fig.height=4}
data %>% 
    filter(!is.na(WCJC004) & hideNA) %>% 
    ggplot(aes(x=WCJC004, fill=WCJC004)) + 
    geom_bar() + 
    coord_flip() + 
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r your_post_tab, eval=varexists(data$WCJC004)}
print_frqtable("WCJC004")
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("WCJC005")`

```{r net_salary, eval=varexists("WCJC005")}
data %>% 
    filter(!is.na(WCJC005)) %>% 
    ggplot(aes(x=WCJC005)) + 
    geom_bar()+ 
    labs(y="Total count") +
    theme_light() +
    theme(axis.title.x = element_blank())

```

```{r net_salary_tab, eval=varexists("WCJC005")}
summary(data$WCJC005)
#print_frqtable(data$WCJC005) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("WCJ005a")`

```{r bonus, eval=varexists("WCJ005a") }
data %>% 
    filter(!is.na(WCJ005a) & hideNA) %>% 
    ggplot(aes(x=WCJ005a, fill=WCJ005a)) + 
    geom_bar()+ 
    scale_fill_brewer(palette="Set1") +
    guides(fill=F) +
    labs(y="Total count") +
    theme_light() +
    theme(axis.title.x = element_blank())
```

```{r bonus_tab, eval=varexists("WCJ005a")}
print_frqtable(data$WCJ005a) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("WCJC008")`

```{r years_employed, eval=varexists("WCJC008")}
data %>% 
    filter(!is.na(WCJC008) & hideNA) %>% 
    ggplot(aes(x=WCJC008,)) + 
    geom_bar()+ 
    coord_flip() + 
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r years_employed_tab, eval=varexists("WCJC008")}
print_frqtable(data$WCJC008) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>



### `r varlabel("WCJC010")`

```{r fullpart_time, eval=varexists("WCJC010") }
data %>% 
    filter(!is.na(WCJC010) & hideNA) %>% 
    ggplot(aes(x=WCJC010)) + 
    geom_bar()+ 
    labs(y="Total count") +
    theme_light() +
    theme(axis.title.x = element_blank())
```

```{r fullpart_time_tab, eval=varexists("WCJC010")}
print_frqtable(data$WCJC010) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>



### `r varlabel("WCJC011")`

```{r temp_fixed, eval=varexists("WCJC011") }
data %>% 
    filter(!is.na(WCJC011) & hideNA) %>% 
    ggplot(aes(x=WCJC011)) + 
    geom_bar()+ 
    labs(y="Total count") +
    theme_light() +
    theme(axis.title.x = element_blank())
```

```{r temp_fixed_tab, eval=varexists("WCJC011")}
print_frqtable(data$WCJC011)
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("G01Q82")`

```{r employ_unit, eval=varexists("G01Q82") }
data %>% 
    filter(!is.na(G01Q82) & hideNA) %>% 
    ggplot(aes(x=G01Q82, fill=G01Q82)) + 
    geom_bar() + 
    coord_flip() + 
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r employ_unit_tab, eval=varexists("G01Q82")}
print_frqtable(data$G01Q82)
```
<p>&nbsp;</p>
<p>&nbsp;</p>



