## Recruitment & Promotion


### `r var_toplabel("WCJC013")`  `r if(lsVarCode) "(WCJC013)" `
<p>&nbsp;</p>


```{r eval=var_exists("WCJC013"), fig.cap=get_caption("WCJC013")}

################################################
# invited promotion
################################################

df.geam %>% 
    print_barplot(WCJC013, lwidth=20)
```


<p>&nbsp;</p>


```{r eval=var_exists("WCJC013")}
df.geam %>% 
    print_frqtable("WCJC013") 
```


<p>&nbsp;</p>


```{r eval=var_exists(c("WCJC013", "SDEM004.bin")), fig.cap=get_caption("WCJC013","SDEM004.bin")}
df.geam %>% 
  print_xbarplot("SDEM004.bin", "WCJC013", legpos = "right", legdir = "vertical", ltitle=F, lwidth=15)
```


<p>&nbsp;</p>


```{r eval=var_exists(c("WCJC013", "SDEM004.bin"))}
df.geam %>% 
    print_xtable("WCJC013", "SDEM004.bin")
```


  
\newpage
  




### `r var_toplabel("WCJC014")`  `r if(lsVarCode) "(WCJC014)" `
<p>&nbsp;</p>


```{r eval=var_exists("WCJC014"), fig.cap=get_caption("WCJC014") }

################################################
#  obtain post
################################################

df.geam %>% 
    print_barplot(WCJC014, lwidth=30, xlangle = 60)
```


<p>&nbsp;</p>


```{r eval=var_exists("WCJC014")}
df.geam %>% 
    print_frqtable("WCJC014") 
```


<p>&nbsp;</p>


```{r eval=var_exists(c("WCJC014", "SDEM004.bin")), fig.cap=get_caption("WCJC014", "SDEM004.bin")}
df.geam %>% 
  print_xbarplot("SDEM004.bin","WCJC014", legpos = "right", legdir = "vertical", ltitle=F, lwidth=15)
```


<p>&nbsp;</p>


```{r eval=var_exists(c("WCJC014", "SDEM004.bin"))}
df.geam %>% 
    print_xtable("WCJC014", "SDEM004.bin")
```
    

\newpage


