## Training


### `r var_toplabel("WCJC019.SQ001.")`  `r if(lsVarCode) "(WCJC019)" `
<p>&nbsp;</p>


```{r eval=var_exists("WCJC019.SQ001."), fig.height=4, fig.cap=get_caption("WCJC019.SQ001.")}

################################################
# opportunities for training available
################################################

df.geam %>%
  select(starts_with("WCJC019.SQ")) %>%
  shorten_label(maxlength = 40) %>% 
  plot_likert(geom.colors="Set1", 
              values="sum.outside", 
              show.n = F, 
              digits = percdigits, 
              show.prc.sign=T, 
              sort.frq = "pos.asc", 
              geom.size = .4,
              reverse.scale = T,
              show.legend = F,
              grid.range = c(1,.2),
              wrap.labels = 50) + 
  theme_light() + 
  theme(legend.position = "bottom", 
        axis.text.x=element_blank(),
        axis.text = element_text(size = 12))



```



\newpage
   

### `r var_toplabel("WCJC021.SQ001.")`  `r if(lsVarCode) "(WCJC021)" `
<p>&nbsp;</p>


```{r eval=var_exists("WCJC021.SQ001."), fig.height=7, fig.width=7, fig.cap=get_caption("WCJC021.SQ001.")}

################################################
# barries to access training
################################################

df.geam %>%
    select(starts_with("WCJC021.SQ")) %>%
    shorten_label(maxlength = 40) %>% 
    plot_likert(geom.colors="Set1", 
              values="sum.outside", 
              show.n = F, 
              show.prc.sign=T, 
              sort.frq = "pos.asc", 
              geom.size = .4,
              reverse.scale = T,
              show.legend = F,
              digits = percdigits,
              grid.range = c(1,.2),
              wrap.labels = 50) + 
  theme_light() + 
  theme(legend.position = "bottom", 
         axis.text.x=element_blank(),
        axis.text = element_text(size = 12))
``` 
    
    
    
\newpage

