# Organizational Culture & Climate


## Perceptions of Recruitment

Includes questions 38-41, codes: BACD003, BACD005, BACD007, GlickMasculCont8

### `r varlabel("BACD003_SQ001")`

```{r eval=varexists("BACD003_SQ001"), fig.height=6, fig.width=10}
data %>%
  select(starts_with("BACD003_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral = NULL) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("BACD005_SQ001")`

```{r eval=varexists("BACD005_SQ001"), fig.height=6, fig.width=10}
data %>%
  select(starts_with("BACD005_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral = NULL) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("BACD007")`

```{r eval=varexists("BACD007"), fig.height=4, fig.width=10}
data %>% 
    filter(!is.na(BACD007) & hideNA) %>% 
    ggplot(aes(x=BACD007, fill=BACD007)) + 
    geom_bar() + 
    coord_flip() + 
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r eval=varexists("BACD007")}
print_frqtable(data$BACD007)
```


<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("GlickMasculCont8_SQ001")`

```{r eval=varexists("GlickMasculCont8_SQ001"), fig.height=6, fig.width=10}
data %>%
  select(starts_with("GlickMasculCont8_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral =3) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>





