## Perceptions of Gender Equality 


Includes questions 32-37, codes: OCPER001, OCPER002, OCPER003, OCPER004, OCPER005 (txt), OCWC002 


### `r varlabel("OCPER001_SQ001")`

```{r perceptionsGE, eval=varexists("OCPER001_SQ001"), fig.height=4, fig.width=10}
data %>%
  select(starts_with("OCPER001_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral=3 ) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>



### `r varlabel("OCPER002_SQ001")`

```{r representWomenMen, eval=varexists("OCPER002_SQ001"), fig.height=4, fig.width=10}
data %>%
  select(starts_with("OCPER002_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 3, cat.neutral=NULL ) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("OCPER003_SQ001")`

```{r diffAllocation, eval=varexists("OCPER003_SQ001"), fig.height=15, fig.width=10}
data %>%
  select(starts_with("OCPER003_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T,  catcount=5, cat.neutral = 3 ) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("OCPER004")`

```{r easeSeniorPos, eval=varexists("OCPER004")}

data %>% 
    filter(!is.na(OCPER004) & hideNA) %>% 
    ggplot(aes(x=OCPER004, fill=OCPER004)) + 
    geom_bar()+ 
    scale_fill_brewer(palette="Set1") +
    coord_flip() + 
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r easeSeniorPos_tab, eval=varexists("OCPER004")}
print_frqtable(data$OCPER004)
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("OCWC002_SQ001")`

```{r lifeWorkplace, eval=varexists("WCWI021_SQ001"), fig.height=12, fig.width=10, fig.height=20}

data %>%
  select(starts_with("OCWC002_S")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount=5, cat.neutral = 3) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>



### `r varlabel("r353q0")`

```{r achievedProgress, eval=varexists("r353q0"), fig.width=10,}

data %>% 
    filter(!is.na(r353q0) & hideNA) %>% 
    ggplot(aes(x=r353q0, fill=r353q0)) + 
    geom_bar() + 
    scale_fill_brewer(palette="Set1") +
    coord_flip() +
    guides(fill=F) +
    labs(y="Total count") +
    guides(fill=F) +
    theme_light() +
    theme(axis.title.y=element_blank())
```

```{r achievedProgress_tab, eval=varexists("r353q0")}
print_frqtable(data$r353q0) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>



### `r varlabel("r59q0_SQ001")`

```{r barriesImplementing, eval=varexists("r59q0_SQ001"), fig.height=12}

data %>%
  select(starts_with("r59q0_SQ0")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount=5, cat.neutral = 3) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>









