# Behavior

## Microagressions


Includes questions 42, codes: BIMA001

### `r varlabel("BIMA001_SQ001")`

```{r ExperienceMicroaggression, eval=varexists("BIMA001_SQ001"), fig.height=10, fig.width=10}

data %>%
  select(starts_with("BIMA001_SQ")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral = NULL) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>


## Bullying Harassment 

Includes questions 43,44, 45, 47, 48  codes: BISB001, BISB002, BISB003, BISB005, BISB006. 

### `r varlabel("BISB001_SQ001")`

```{r ConfidenceReporting, eval=varexists("BISB001_SQ001"), fig.height=6, fig.width=10}

data %>%
  select(starts_with("BISB001")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral = NULL) + 
  theme_light()

```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("BISB003")`

```{r HasExperiencedGBV, eval=varexists("BISB003")}

data %>% 
    filter(!is.na(BISB003) & hideNA) %>% 
    ggplot(aes(x=BISB003)) + 
    geom_bar()+ 
    labs(y="Total count") +
    theme_light() +
    theme(axis.title.x = element_blank())
```


```{r HasExperiencedGBV_tab, eval=varexists("BISB003")}
print_frqtable(data$BISB003) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>


### `r varlabel("BISB004_SQ001")`

```{r GBVWhom, eval=varexists("BISB004_SQ001")}

data %>%
  select(starts_with("BISB004")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral = NULL) + 
  theme_light()
```


```{r eval=varexists("BISB004")}
print_frqtable(data$BISB004) 
```
<p>&nbsp;</p>
<p>&nbsp;</p>



### `r varlabel("Neosexism_SQ002")`
(Neosexism scale)
```{r Neosexism, eval=varexists("Neosexism_SQ002"), fig.height=12}

data %>%
  select(starts_with("Neosexism_SQ0")) %>%
  plot_likert(geom.colors="Set1", values="show", show.prc.sign=T, catcount = 4, cat.neutral = NULL) + 
  theme_light()
```


<p>&nbsp;</p>
<p>&nbsp;</p>


